from ast_nodes import *
StatementList0 = StatementListNode()
Var0 = VarNode("a")
IntLit0 = IntLitNode("5")
IntLit1 = IntLitNode("7")
BinaryOp0 = BinaryOpNode("*", IntLit0, IntLit1)
IntLit2 = IntLitNode("3")
IntLit3 = IntLitNode("5")
BinaryOp1 = BinaryOpNode("-", IntLit2, IntLit3)
Var1 = VarNode("b")
IntLit4 = IntLitNode("143")
IntLit5 = IntLitNode("15")
BinaryOp2 = BinaryOpNode("-", IntLit4, IntLit5)
IntLit6 = IntLitNode("27")
BinaryOp3 = BinaryOpNode("*", BinaryOp2, IntLit6)
Assign0 = AssignNode(Var1, BinaryOp3)
StatementList0.append(Assign0)
Var2 = VarNode("c")
Var3 = VarNode("a")
Var4 = VarNode("b")
BinaryOp4 = BinaryOpNode("/", Var3, Var4)
Assign1 = AssignNode(Var2, BinaryOp4)
StatementList0.append(Assign1)
Var5 = VarNode("d")
Var6 = VarNode("a")
Var7 = VarNode("b")
BinaryOp5 = BinaryOpNode("+", Var6, Var7)
Var8 = VarNode("c")
BinaryOp6 = BinaryOpNode("+", BinaryOp5, Var8)
Assign2 = AssignNode(Var5, BinaryOp6)
StatementList0.append(Assign2)
Var9 = VarNode("e")
Var10 = VarNode("d")
IntLit7 = IntLitNode("153")
BinaryOp7 = BinaryOpNode("*", Var10, IntLit7)
Assign3 = AssignNode(Var9, BinaryOp7)
StatementList0.append(Assign3)
traversal = open("out.traversal", "w")
StatementList0.print(traversal, 0)
